PRETRAINED_VARIANTS = {
    "resnet18": ["IMAGENET1K_V1"],
    "resnet34": ["IMAGENET1K_V1"],
    "resnet50": ["IMAGENET1K_V1", "IMAGENET1K_V2"],
    "resnet101": ["IMAGENET1K_V1", "IMAGENET1K_V2"],
    "resnet152": ["IMAGENET1K_V1", "IMAGENET1K_V2"],
    "densenet121": ["IMAGENET1K_V1"],
    "densenet169": ["IMAGENET1K_V1"],
    "densenet161": ["IMAGENET1K_V1"],
    "densenet201": ["IMAGENET1K_V1"],
    "mobilenet_v2": ["IMAGENET1K_V1"],
    "mobilenet_v3_small": ["IMAGENET1K_V1"],
    "mobilenet_v3_large": ["IMAGENET1K_V1"],
    "efficientnet_b0": ["IMAGENET1K_V1"],
    "efficientnet_b1": ["IMAGENET1K_V1"],
    "efficientnet_b3": ["IMAGENET1K_V1"],
    "efficientnet_b7": ["IMAGENET1K_V1"],
    "convnext_tiny": ["IMAGENET1K_V1"],
    "convnext_small": ["IMAGENET1K_V1"],
    "convnext_base": ["IMAGENET1K_V1"],
    "convnext_large": ["IMAGENET1K_V1"],
    "vit_b_16": ["IMAGENET1K_V1", "IMAGENET1K_SWAG_E2E_V1", "IMAGENET1K_SWAG_LINEAR_V1"],
    "vit_b_32": ["IMAGENET1K_V1"],
    "vit_l_16": ["IMAGENET1K_V1", "IMAGENET1K_SWAG_E2E_V1", "IMAGENET1K_SWAG_LINEAR_V1"],
    "swin_t": ["IMAGENET1K_V1"],
    "swin_s": ["IMAGENET1K_V1"],
    "swin_b": ["IMAGENET1K_V1"],
    "regnet_y_400mf": ["IMAGENET1K_V1"],
    "regnet_y_800mf": ["IMAGENET1K_V1"],
    "regnet_y_1_6gf": ["IMAGENET1K_V1"],
    "regnet_y_3_2gf": ["IMAGENET1K_V1"],
    "regnet_y_8gf": ["IMAGENET1K_V1"],
    "alexnet": ["IMAGENET1K_V1"],
    "vgg11": ["IMAGENET1K_V1"],
    "vgg13": ["IMAGENET1K_V1"],
    "vgg16": ["IMAGENET1K_V1", "IMAGENET1K_FEATURES"],
    "vgg19": ["IMAGENET1K_V1"],
    "squeezenet1_0": ["IMAGENET1K_V1"],
    "squeezenet1_1": ["IMAGENET1K_V1"],
    "inception_v3": ["IMAGENET1K_V1"],
}

TEXT_MODELS = [
    "bert-base-uncased",
    "bert-large-uncased",
    "allenai/scibert_scivocab_uncased",
    "roberta-base",
    "roberta-large",
    "dmis-lab/biobert-base-cased-v1.1",
    "nlpaueb/legal-bert-base-uncased",
    "yiyanghkust/finbert-tone",
    "albert-base-v2",
    "albert-large-v2",
    "albert-xlarge-v2",
    "albert-xxlarge-v2",
    "microsoft/deberta-base",
    "microsoft/deberta-large",
    "microsoft/deberta-v2-xxlarge",
    "microsoft/deberta-v3-base",
    "microsoft/deberta-v3-large",
    "microsoft-mdeberta-v3-base",
    "microsoft-deberta-base-mnli",
    "allenai/longformer-base-4096",
    "allenai/longformer-large-4096",
    "distilbert-base-uncased",
    "distilbert-base-cased",
    "distilbert-base-uncased-distilled-squad",
    "distilbert-base-cased-distilled-squad",
    "t5-small",
    "t5-base",
    "t5-large",
    "t5-3l",
    "t5-11l",
    "facebook/bart-base",
    "facebook/bart-large",
    "facebook/bart-large-cnn",
    "gpt2",
    "gpt-neo-125m",
    "gpt-neo-1.3b",
    "gpt-neo-2.7b"
]
